const API='https://syntra-zeta-nine.vercel.app/api/customer-results';
const el=id=>document.getElementById(id);
const E={search:el('search'),list:el('list'),selected:el('selected'),selectedName:el('selectedName'),selectedMeta:el('selectedMeta'),refresh:el('refresh'),loading:el('loading'),result:el('result'),marketOrb:el('marketOrb'),marketName:el('marketName'),marketCode:el('marketCode'),sourceDateChip:el('sourceDateChip'),leadBadge:el('leadBadge'),heroResult:el('heroResult'),source:el('source'),signalRing:el('signalRing'),ringLevel:el('ringLevel'),ringLabel:el('ringLabel'),doubleLevelBar:el('doubleLevelBar'),siblingLevelBar:el('siblingLevelBar'),doubleFill:el('doubleFill'),siblingFill:el('siblingFill'),heroInsight:el('heroInsight'),miniMaster:el('miniMaster'),miniRud:el('miniRud'),miniReserve:el('miniReserve'),miniHistory:el('miniHistory'),masterDigit:el('masterDigit'),masterCount:el('masterCount'),win:el('win'),reserve:el('reserve'),win7:el('win7'),rudMain:el('rudMain'),rudSub:el('rudSub'),doubleLevel:el('doubleLevel'),siblingLevel:el('siblingLevel'),doubleExplain:el('doubleExplain'),siblingExplain:el('siblingExplain'),doublePicks:el('doublePicks'),siblingPicks:el('siblingPicks'),harmPicks:el('harmPicks'),pair2:el('pair2'),pair3:el('pair3'),baseResult:el('baseResult'),baseDate:el('baseDate'),toast:el('toast')};
let all=[],filtered=[],current=null,currentDrill={pair2:[],pair3:[]};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const arr=x=>Array.isArray(x)?x:(x?[x]:[]);
const spaced=s=>String(s||'').split('').join(' • ');
const uniq=s=>[...new Set(String(s||'').split('').filter(d=>/\d/.test(d)))];
const pairKey=p=>String(p||'').split('').sort().join('');
const fmt=s=>{if(!s)return'-';const d=new Date(s+'T00:00:00');return new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'2-digit'}).format(d)};
function flagForMarket(name,key=''){const s=`${name||''} ${key||''}`.toLowerCase();const rules=[[/ลาว|lao|สาละวัน|เวียงจันท|หลวงพระบาง|ปากเซ|จำปาสัก/,'🇱🇦'],[/ฮานอย|เวียดนาม|vietnam|hanoi/,'🇻🇳'],[/ฮั่งเส็ง|ฮ่องกง|hong|hang/,'🇭🇰'],[/ไต้หวัน|taiwan/,'🇹🇼'],[/จีน|china|shanghai/,'🇨🇳'],[/นิเคอิ|นิคเคอิ|ญี่ปุ่น|nikkei|japan/,'🇯🇵'],[/เกาหลี|korea|kospi/,'🇰🇷'],[/สิงคโปร์|singapore/,'🇸🇬'],[/ดาวโจนส์|ดาวโจน|dow|nasdaq|usa/,'🇺🇸'],[/ไทย|ธกส|ออมสิน|thailand/,'🇹🇭'],[/อินเดีย|india/,'🇮🇳'],[/อังกฤษ|ftse|uk/,'🇬🇧'],[/เยอรมัน|dax|germany/,'🇩🇪']];for(const [re,f] of rules)if(re.test(s))return f;return'🌐'}
function marketLetter(name){const s=String(name||'').trim();return s?(/[A-Za-z]/.test(s[0])?s[0].toUpperCase():'S'):'S'}
function shadow(r){return r?.metadata?.shadow||{}}
function relationPicks(r,type){const sh=shadow(r),ctx=sh.context||{},sig=ctx.signalOutputs||{};if(type==='double')return arr(sh.double_picks||sig.doublePicks||r?.metadata?.double_picks).map(String).slice(0,4);if(type==='sibling')return arr(sh.sibling_picks||sig.siblingPicks).map(String).slice(0,5);if(type==='harm')return arr(sh.harm_picks||sig.harmPicks).map(String).slice(0,4);return[]}
function level(score){score=Number(score||0);if(score<18)return'อ่อน';if(score<25)return'เฝ้า';if(score<40)return'เด่น';return'แรง'}
function levelExplain(kind,score){const l=level(score);if(kind==='double'){if(l==='อ่อน')return'สัญญาณเบิ้ลยังเบา ใช้เป็นตัวประกอบ';if(l==='เฝ้า')return'เริ่มมีแรงเบิ้ล ให้จับตาชุดซ้ำ';if(l==='เด่น')return'หลักฐานหลายทางหนุนเบิ้ลรอบนี้';return'เบิ้ลเป็นโครงสร้างที่ระบบให้น้ำหนักสูง'}if(l==='อ่อน')return'แรงพี่น้องยังน้อย ใช้ประกอบการคัด';if(l==='เฝ้า')return'เริ่มเห็นแรงคู่ติดกันในรอบนี้';if(l==='เด่น')return'กลุ่มเลขติดกันมีน้ำหนักเด่นกว่าปกติ';return'พี่น้องเป็นสัญญาณนำที่แรงของรอบนี้'}
function sigPills(a){return a.length?a.map(x=>`<span class="sigPill">${esc(x)}</span>`).join(''):'<span style="font-size:8px;color:#89a49d">ยังไม่มีชุดเด่น</span>'}
function master(pairs,strong,rud){const f={};arr(pairs).forEach(p=>String(p).split('').forEach(d=>f[d]=(f[d]||0)+1));const pref=[...String(strong||''),...String(rud||'')];let b='-',n=0;Object.entries(f).forEach(([d,c])=>{if(c>n||(c===n&&pref.indexOf(d)>=0&&(pref.indexOf(b)<0||pref.indexOf(d)<pref.indexOf(b)))){b=d;n=c}});return{d:b,n}}
function meterForLevel(l){return({อ่อน:22,เฝ้า:43,เด่น:69,แรง:91,ผสม:78})[l]||30}
function historyCount(v){if(Array.isArray(v))return v.length;if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'){const n=Number(v);return Number.isFinite(n)?n:(v.trim()?1:0)}if(v&&typeof v==='object'){for(const k of ['count','length','total','used']){const n=Number(v[k]);if(Number.isFinite(n)&&n>=0)return n}for(const k of ['rows','items','history','results'])if(Array.isArray(v[k]))return v[k].length;return 0}return 0}
function leadSignal(sh){const ds=Number(sh.double_score||0),ss=Number(sh.sibling_score||0),dl=level(ds),sl=level(ss);if(Math.abs(ds-ss)<=4&&Math.max(ds,ss)>=18)return{name:'เบิ้ล+พี่น้อง',level:'ผสม',score:Math.max(ds,ss),doubleLevel:dl,siblingLevel:sl};return ds>=ss?{name:'เบิ้ล',level:dl,score:ds,doubleLevel:dl,siblingLevel:sl}:{name:'พี่น้อง',level:sl,score:ss,doubleLevel:dl,siblingLevel:sl}}

/* Drill v2: RUD main/sub are the two axes. Reverse pairs count as the same pair. */
function buildPair2(r){const win=uniq(r.win6),rud=uniq(r.rud).slice(0,2);if(win.length<2||rud.length<2)return arr(r.pair2).map(String).slice(0,9);const out=[],seen=new Set();for(const axis of rud){for(const d of win){if(d===axis)continue;const p=axis+d,k=pairKey(p);if(seen.has(k))continue;seen.add(k);out.push(p)}}return out.slice(0,9)}
function scorePair(r,p,idx){const old=arr(r.pair2).map(String),key=pairKey(p),strong=pairKey(r.strong2||'');let s=100-idx;if(strong&&key===strong)s+=90;const oi=old.findIndex(x=>pairKey(x)===key);if(oi>=0)s+=70-(oi*8);const sd=String(r.strong2||'');for(const d of p)if(sd.includes(d))s+=12;return s}
function hundredPreference(r){const win=uniq(r.win6),pref=[];const push=d=>{if(win.includes(d)&&!pref.includes(d))pref.push(d)};push(String(r.strong3||'')[0]);arr(r.pair3).map(String).forEach(x=>push(x[0]));String(r.strong2||'').split('').forEach(push);win.forEach(push);return pref}
function buildPair3(r,pair2){const ranked=pair2.map((p,i)=>({p,s:scorePair(r,p,i)})).sort((a,b)=>b.s-a.s).slice(0,5);const hp=hundredPreference(r),used=new Set(),out=[];ranked.forEach((o,i)=>{const choices=[...hp.slice(i),...hp.slice(0,i)];let h=choices.find(d=>!o.p.includes(d)&&!used.has(d+o.p));if(!h)h=choices.find(d=>!used.has(d+o.p))||hp[0]||String(r.win6||'')[0]||'0';let pair=o.p;const old3=arr(r.pair3).map(String),rev=pair[1]+pair[0];const revHit=old3.some(t=>t.slice(-2)===rev);const dirHit=old3.some(t=>t.slice(-2)===pair);if(revHit&&!dirHit)pair=rev;const tri=h+pair;used.add(tri);out.push(tri)});return out.slice(0,5)}
function drillFor(r){const pair2=buildPair2(r),pair3=buildPair3(r,pair2);return{pair2,pair3}}

function renderList(){const q=E.search.value.trim().toLowerCase();filtered=all.filter(x=>!q||String(x.market_name).toLowerCase().includes(q)||String(x.market_key).toLowerCase().includes(q));E.list.innerHTML=filtered.length?filtered.map(x=>`<button class="item ${current&&x.market_key===current.market_key?'active':''}" data-k="${esc(x.market_key)}"><span>${flagForMarket(x.market_name,x.market_key)} ${esc(x.market_name)}</span><small>${esc(x.source_top3)}-${esc(x.source_bottom2)}</small></button>`).join(''):'<div class="loading">ไม่พบตลาด</div>';E.list.classList.add('show');E.list.querySelectorAll('.item').forEach(b=>b.onclick=()=>{selectMarket(all.find(x=>x.market_key===b.dataset.k));E.search.value='';E.list.classList.remove('show')})}
function selectMarket(r){if(!r)return;current=r;currentDrill=drillFor(r);localStorage.setItem('syntrax_market',r.market_key);const flag=flagForMarket(r.market_name,r.market_key),sh=shadow(r),rud=String(r.rud||''),dp=relationPicks(r,'double'),sp=relationPicks(r,'sibling'),hp=relationPicks(r,'harm'),lead=leadSignal(sh),dl=lead.doubleLevel,sl=lead.siblingLevel,m=master(currentDrill.pair2,r.strong2,r.rud),meter=meterForLevel(lead.level),hCount=historyCount(r.history_used);
E.selectedName.textContent=`${flag} ${r.market_name}`;E.selectedMeta.textContent=` · ${r.source_top3}-${r.source_bottom2}`;E.marketOrb.textContent=marketLetter(r.market_name);E.marketName.textContent=r.market_name;E.marketCode.textContent=String(r.market_key||'SHADOW MARKET').replaceAll('_',' ').toUpperCase();E.sourceDateChip.textContent=r.source_draw_date||'-';E.leadBadge.textContent=`${lead.name} · ${lead.level}`;E.heroResult.textContent=`${r.source_top3} - ${r.source_bottom2}`;E.source.innerHTML=`ฐานล่าสุด <b>${fmt(r.source_draw_date)}</b>`;E.ringLevel.textContent=lead.level;E.ringLabel.textContent=lead.name;E.signalRing.style.setProperty('--p',`${meter*3.6}deg`);E.doubleLevelBar.textContent=dl;E.siblingLevelBar.textContent=sl;E.doubleFill.style.width=`${meterForLevel(dl)}%`;E.siblingFill.style.width=`${meterForLevel(sl)}%`;E.heroInsight.innerHTML=lead.level==='ผสม'?'<b>✦ สัญญาณผสม: เบิ้ล + พี่น้อง</b> · ทั้งสองโครงสร้างมีน้ำหนักใกล้กันในรอบนี้':`<b>✦ สัญญาณนำ: ${lead.name} ${lead.level}</b> · ${lead.name==='เบิ้ล'?levelExplain('double',sh.double_score):levelExplain('sibling',sh.sibling_score)}`;
E.masterDigit.textContent=m.d;E.masterCount.textContent=m.n?`อยู่ใน ${m.n}/${currentDrill.pair2.length} คู่เจาะ 2 · แกนรูด ${spaced(r.rud)}`:'คัดจากเจาะ 2 และรูด';E.miniMaster.textContent=m.d;E.miniRud.textContent=spaced(r.rud)||'-';E.miniReserve.textContent=r.reserve7||'-';E.miniHistory.textContent=hCount?`${hCount} งวด`:'-';E.win.innerHTML=String(r.win6||'').split('').map(d=>`<div class="wd">${esc(d)}</div>`).join('');E.reserve.textContent=r.reserve7||'-';E.win7.textContent=r.win7||'-';E.rudMain.textContent=rud[0]||'-';E.rudSub.textContent=rud[1]||'-';E.doubleLevel.textContent=dl;E.siblingLevel.textContent=sl;E.doubleExplain.textContent=levelExplain('double',sh.double_score);E.siblingExplain.textContent=levelExplain('sibling',sh.sibling_score);E.doublePicks.innerHTML=sigPills(dp);E.siblingPicks.innerHTML=sigPills(sp);E.harmPicks.innerHTML=sigPills(hp);E.pair2.innerHTML=currentDrill.pair2.map((p,i)=>`<div class="pair ${i<5?'hot':''}">${esc(p)}</div>`).join('');E.pair3.innerHTML=currentDrill.pair3.map((p,i)=>`<div class="tri ${i===0?'hot':''}">${esc(p)}</div>`).join('');E.baseResult.textContent=`${r.source_top3}-${r.source_bottom2}`;E.baseDate.textContent=fmt(r.source_draw_date);E.result.style.display='block';E.list.classList.remove('show')}
function toast(msg='คัดลอกแล้ว'){E.toast.textContent=msg;E.toast.classList.add('show');setTimeout(()=>E.toast.classList.remove('show'),1400)}
async function copyText(x){try{await navigator.clipboard.writeText(x)}catch{const t=document.createElement('textarea');t.value=x;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}toast()}
function buildCopy(){if(!current)return'';const r=current,dp=relationPicks(r,'double'),sp=relationPicks(r,'sibling'),hp=relationPicks(r,'harm'),m=master(currentDrill.pair2,r.strong2,r.rud),sh=shadow(r);return `🍀 SyntraX | ${r.market_name}\n${r.source_top3}-${r.source_bottom2}\n\n💎 ตัวเด่น ${m.d}\n🔥 WIN6 ${spaced(r.win6)}\n⚡ รูด ${spaced(r.rud)}\n🎲 เบิ้ล ${level(sh.double_score)} · ${dp.join(' • ')||'-'}\n👥 พี่น้อง ${level(sh.sibling_score)} · ${sp.join(' • ')||'-'}\n🪞 หาม เฝ้า ABA · ${hp.join(' • ')||'-'}\n🎯 เจาะ 2 ${currentDrill.pair2.join(' • ')}\n🎯 เจาะ 3 ${currentDrill.pair3.join(' • ')}\nสำรอง ${r.reserve7||'-'} · WIN7 ${r.win7||'-'}`}
async function shareAll(){const text=buildCopy();if(!text)return;if(navigator.share){try{await navigator.share({title:`SyntraX | ${current.market_name}`,text});return}catch(e){if(e?.name==='AbortError')return}}copyText(text)}
E.search.onfocus=renderList;E.search.oninput=renderList;E.selected.onclick=()=>E.list.classList.contains('show')?E.list.classList.remove('show'):renderList();E.refresh.onclick=()=>location.reload();el('copyPairs').onclick=()=>current&&copyText(currentDrill.pair2.join(' • '));el('copyAll').onclick=()=>copyText(buildCopy());el('share').onclick=shareAll;document.addEventListener('click',e=>{if(!e.target.closest('.selector'))E.list.classList.remove('show')});el('navHome').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});el('navMarket').onclick=()=>{document.getElementById('marketSection').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>E.search.focus(),350)};el('navCopy').onclick=()=>copyText(buildCopy());el('navRefresh').onclick=()=>location.reload();
(async()=>{try{const r=await fetch(API,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'โหลดข้อมูลไม่ได้');all=d.results||[];E.loading.style.display='none';const saved=localStorage.getItem('syntrax_market');selectMarket(all.find(x=>x.market_key===saved)||all.find(x=>x.market_name==='ลาวพัฒนา')||all[0])}catch(e){E.loading.textContent='โหลดข้อมูลไม่ได้ · '+e.message}})();